#!/bin/sh

# Xcode Cloud pre-xcodebuild script
# This runs before xcodebuild and ensures Node.js is in PATH
# Located in mobile/ios/ci_scripts/ (relative to workspace)

set -e

echo "🔧 Preparing build environment for xcodebuild..."
echo "Current directory: $(pwd)"

# Ensure Node.js is in PATH (node@20 is keg-only in Homebrew)
if ! command -v node &> /dev/null; then
    if [ -d "/usr/local/opt/node@20/bin" ]; then
        export PATH="/usr/local/opt/node@20/bin:$PATH"
        echo "✅ Added node@20 to PATH (Intel)"
    elif [ -d "/opt/homebrew/opt/node@20/bin" ]; then
        export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
        echo "✅ Added node@20 to PATH (Apple Silicon)"
    else
        echo "❌ Error: Node.js not found and not in expected locations"
        exit 1
    fi
fi

# Verify Node.js is available
if ! command -v node &> /dev/null; then
    echo "❌ Error: Node.js still not found in PATH"
    echo "PATH: $PATH"
    exit 1
fi

echo "✅ Node.js version: $(node --version)"
echo "✅ npm version: $(npm --version)"
echo "✅ Node.js path: $(command -v node)"

# Update .xcode.env to point to the correct node binary
# Navigate to ios directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IOS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$IOS_DIR"

NODE_BINARY=$(command -v node)
echo "Updating .xcode.env with NODE_BINARY=$NODE_BINARY"

# Create or update .xcode.env.local with the correct node path
cat > .xcode.env.local << EOF
# Auto-generated by ci_pre_xcodebuild.sh
# This file ensures Node.js is available during Xcode build scripts
export NODE_BINARY=$NODE_BINARY
EOF

echo "✅ .xcode.env.local created/updated"
echo "✅ Build environment ready!"

